# Generated by Django 6.0.6 on 2026-06-29 00:32

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Planta 1, Planta -1, Terraza', max_length=50, verbose_name='Nombre del nivel')),
                ('floor_number', models.IntegerField(help_text='Número entero que identifica la planta (0 = planta baja, -1 = sótano, etc.)', verbose_name='Número de planta')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'db_table': 'levels',
                'ordering': ['floor_number'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Tarifa Básica, Tarifa Premium Fin de Semana', max_length=100, verbose_name='Nombre de la tarifa')),
                ('tariff_type', models.CharField(choices=[('basic', 'Básico'), ('premium', 'Premium'), ('monthly', 'Mensual')], default='basic', max_length=10, verbose_name='Tipo de tarifa')),
                ('price_per_hour', models.DecimalField(decimal_places=2, help_text='Precio aplicado por hora para tarifas Básica y Premium.', max_digits=8, verbose_name='Precio por hora (€)')),
                ('price_per_month', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio fijo mensual. Solo aplica para tarifa Mensual.', max_digits=8, verbose_name='Precio por mes (€)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'db_table': 'tariffs',
                'ordering': ['tariff_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número de plaza')),
                ('status', models.CharField(choices=[('free', '🟢 Libre'), ('occupied', '🔴 Ocupado'), ('reserved', '🔵 Reservado')], db_index=True, default='free', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='parking.level', verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Plaza de aparcamiento',
                'verbose_name_plural': 'Plazas de aparcamiento',
                'db_table': 'parking_spots',
                'ordering': ['level', 'number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(db_index=True, max_length=20, verbose_name='Matrícula')),
                ('entry_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Hora de entrada')),
                ('exit_time', models.DateTimeField(blank=True, help_text='Nulo si el vehículo sigue dentro del parking.', null=True, verbose_name='Hora de salida')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculado automáticamente al hacer check-out.', max_digits=10, verbose_name='Importe total (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='parking.parkingspot', verbose_name='Plaza')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='parking.tariff', verbose_name='Tarifa aplicada')),
            ],
            options={
                'verbose_name': 'Sesión de vehículo',
                'verbose_name_plural': 'Sesiones de vehículos',
                'db_table': 'vehicle_sessions',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='parkingspot',
            constraint=models.UniqueConstraint(fields=('level', 'number'), name='unique_spot_per_level'),
        ),
        migrations.AddIndex(
            model_name='vehiclesession',
            index=models.Index(fields=['license_plate', 'entry_time'], name='idx_plate_entry'),
        ),
        migrations.AddIndex(
            model_name='vehiclesession',
            index=models.Index(condition=models.Q(('exit_time__isnull', True)), fields=['exit_time'], name='idx_exit_time'),
        ),
    ]
